spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/parking
    username: postgres
    password: 123qweR

  security:
     oauth2:
       client:
         registration:
           github:
              client-id: Ov23liUegaLVGQkiQhap
              client-secret: d42c9ebb2ef4b972f149b7a0639823ece9ec804a
              scope: read:user, repo
              redirect-uri: "http://localhost:8080/callback"
              authorization-grant-type: authorization_code
              client-authentication-method: basic
              provider: github
         provider:
            github:
              authorization-uri: https://github.com/login/oauth/authorize
              token-uri: https://github.com/login/oauth/access_token
              user-info-uri: https://api.github.com/user
              user-name-attribute: login
server:
  port: 8080